export const countries = [
  {
    slug: 'uae',
    name: 'United Arab Emirates',
    isoCode: 'AE',
    region: 'GCC',
    color: '#1F7A6C',
    tagline: 'The busiest corridor in our network',
    description:
      'The UAE is our highest-volume destination for overseas jobs, with steady demand across construction, hospitality, healthcare, and technical trades in Dubai, Abu Dhabi, and Sharjah. Employers here typically offer 2-year renewable contracts with accommodation or a housing allowance included.',
    whyWorkHere:
      'Tax-free salaries, a large existing Indian community, and direct flights from most major Indian cities make the UAE the easiest first move for most candidates. Demand is consistent year-round rather than seasonal, and most of our employer partners have worked with Alzareen International for 5+ years.',
    roleCount: 118,
    salaryRange: 'AED 2,500–6,000/month',
    cities: ['Dubai', 'Abu Dhabi', 'Sharjah'],
    topProfessions: ['Construction', 'Hospitality', 'Healthcare', 'Technical Trades'],
    visaNote:
      'Employer-sponsored work visa, typically a 2-year renewable contract. Requires a medical fitness test and an Emirates ID application after arrival.',
    applicationSteps: [
      'Submit your resume and trade certificates for review',
      'Interview (in person or video) with the hiring employer',
      'Offer letter issued, followed by medical test and visa filing',
      'Travel booking and pre-departure briefing',
    ],
    faqs: [
      {
        q: 'How long does the UAE visa process take?',
        a: 'Typically 3–6 weeks from offer letter to visa stamping, depending on the employer and role.',
      },
      {
        q: 'Is accommodation provided?',
        a: 'Most construction, hospitality, and trade employers include shared accommodation or a monthly housing allowance — this is confirmed in your offer letter before you accept.',
      },
    ],
  },
  {
    slug: 'saudi-arabia',
    name: 'Saudi Arabia',
    isoCode: 'SA',
    region: 'GCC',
    color: '#8B4B2B',
    tagline: 'Fast-growing in facilities and logistics',
    description:
      'Saudi Arabia\u2019s Vision 2030 infrastructure push is driving consistent hiring in facilities management, retail, and industrial roles across Riyadh, Jeddah, and Dammam. It\u2019s currently our second-largest destination by role volume.',
    whyWorkHere:
      'Large-scale giga-projects mean multi-year role pipelines rather than one-off openings, and salaries for skilled trades have risen steadily over the past three years as demand has outpaced local supply.',
    roleCount: 96,
    salaryRange: 'SAR 2,000–5,000/month',
    cities: ['Riyadh', 'Jeddah', 'Dammam'],
    topProfessions: ['Facilities Management', 'Retail', 'Industrial', 'Logistics'],
    visaNote:
      'Employer-sponsored work visa processed under the Wafid system, with a medical fitness clearance required before travel.',
    applicationSteps: [
      'Resume and experience certificate review',
      'Employer interview and role confirmation',
      'Wafid medical clearance and visa filing',
      'Travel and airport pickup coordination',
    ],
    faqs: [
      {
        q: 'Do I need Arabic to work in Saudi Arabia?',
        a: 'No — most industrial, facilities, and logistics roles operate in English or Hindi/Urdu on-site; Arabic is not a requirement for the roles we place.',
      },
    ],
  },
  {
    slug: 'qatar',
    name: 'Qatar',
    isoCode: 'QA',
    region: 'GCC',
    color: '#2C4A7C',
    tagline: 'Strong healthcare and aviation demand',
    description:
      'Doha continues to hire steadily for hospital support roles, aviation ground services, and engineering positions tied to ongoing infrastructure and airport expansion work.',
    whyWorkHere:
      'Qatar offers some of the highest salary bands in the GCC for healthcare and engineering roles, alongside a smaller, more centralised job market that makes onboarding faster than larger destinations.',
    roleCount: 52,
    salaryRange: 'QAR 3,000–7,000/month',
    cities: ['Doha', 'Al Wakrah'],
    topProfessions: ['Healthcare', 'Engineering', 'Aviation Ground Services'],
    visaNote:
      'Employer-sponsored residence permit, processed alongside a Qatar-specific medical and biometric check on arrival.',
    applicationSteps: [
      'Credential and licence verification (for healthcare roles)',
      'Employer interview',
      'Offer letter and residence permit filing',
      'Biometric registration on arrival',
    ],
    faqs: [
      {
        q: 'Are nursing licences recognised in Qatar?',
        a: 'Yes, subject to Qatar Council for Healthcare Practitioners (QCHP) licensing — our documentation team handles this filing as part of the placement.',
      },
    ],
  },
  {
    slug: 'kuwait',
    name: 'Kuwait',
    isoCode: 'KW',
    region: 'GCC',
    color: '#6B4C9A',
    tagline: 'Established base in oil, gas, and trades',
    description:
      'Kuwait remains a reliable destination for skilled trades and logistics roles, with a long-standing partner base around Kuwait City and Ahmadi.',
    whyWorkHere:
      'Kuwait\u2019s oil and gas sector has some of the longest-tenured employer relationships in our network — several partners have re-hired through Alzareen International every year since 2018.',
    roleCount: 41,
    salaryRange: 'KWD 250–380/month',
    cities: ['Kuwait City', 'Ahmadi'],
    topProfessions: ['Oil & Gas Support', 'Logistics', 'Skilled Trades'],
    visaNote:
      'Employer-sponsored work permit (Article 18), with pre-departure medical and Kuwait-side fingerprinting after arrival.',
    applicationSteps: [
      'Trade test or experience verification',
      'Employer interview',
      'Article 18 permit filing and medical test',
      'Travel and fingerprint registration on arrival',
    ],
    faqs: [
      {
        q: 'What is Article 18 in Kuwait?',
        a: 'It\u2019s the standard private-sector employment visa category most of our Kuwait placements fall under, sponsored directly by the hiring employer.',
      },
    ],
  },
  {
    slug: 'bahrain',
    name: 'Bahrain',
    isoCode: 'BH',
    region: 'GCC',
    color: '#B9862B',
    tagline: 'Smaller market, steady openings',
    description:
      'A smaller but consistent market for facilities, hospitality, and banking-support roles concentrated around Manama.',
    whyWorkHere:
      'Bahrain\u2019s smaller market means faster employer decisions — most offers here are confirmed within 2 weeks of interview, quicker than most other GCC destinations.',
    roleCount: 28,
    salaryRange: 'BHD 250–420/month',
    cities: ['Manama'],
    topProfessions: ['Banking Support', 'Hospitality', 'Facilities Management'],
    visaNote: 'Employer-sponsored work permit through the LMRA, typically processed in 3–5 weeks.',
    applicationSteps: [
      'Resume review and employer shortlist',
      'Interview and offer confirmation',
      'LMRA work permit filing',
      'Travel booking',
    ],
    faqs: [],
  },
  {
    slug: 'oman',
    name: 'Oman',
    isoCode: 'OM',
    region: 'GCC',
    color: '#2E8B8B',
    tagline: 'Growing construction and logistics hiring',
    description:
      'Infrastructure and logistics investment around Muscat and Sohar is opening up steady construction and warehousing roles.',
    whyWorkHere:
      'Oman\u2019s port and logistics expansion around Sohar is creating new role categories we didn\u2019t place two years ago — an easier market to enter early for warehousing and logistics candidates.',
    roleCount: 33,
    salaryRange: 'OMR 250–400/month',
    cities: ['Muscat', 'Sohar'],
    topProfessions: ['Construction', 'Healthcare', 'Logistics'],
    visaNote:
      'Employer-sponsored work visa, with labour clearance and medical fitness certification required before travel.',
    applicationSteps: [
      'Experience and certificate review',
      'Employer interview',
      'Labour clearance and visa filing',
      'Medical test and travel',
    ],
    faqs: [],
  },
  {
    slug: 'germany',
    name: 'Germany',
    isoCode: 'DE',
    region: 'Other Destinations',
    color: '#55627A',
    tagline: 'Our first and largest EU destination',
    description:
      'Skilled-trade and elder-care roles across Stuttgart, Berlin, and Munich, usually paired with recognised qualification and basic language preparation before departure.',
    whyWorkHere:
      'Germany offers EU labour protections, a clear path to permanent residency after several years, and among the highest take-home pay in our network once cost of living is accounted for.',
    roleCount: 34,
    salaryRange: '€2,200–3,500/month',
    cities: ['Stuttgart', 'Berlin', 'Munich'],
    topProfessions: ['Skilled Trades', 'Elder Care', 'Manufacturing'],
    visaNote:
      'National (Type D) work visa tied to a recognised qualification, plus a basic German language requirement (A2/B1) for some roles.',
    applicationSteps: [
      'Qualification recognition check',
      'Language prep (A2/B1, where required)',
      'Employer interview and contract signing',
      'National visa filing at the German consulate',
    ],
    faqs: [
      {
        q: 'Do I need to speak German before I go?',
        a: 'Most elder-care roles require A2/B1 level German; skilled-trade roles vary by employer — we confirm the requirement before you start language prep.',
      },
    ],
  },
  {
    slug: 'turkey',
    name: 'Turkey',
    isoCode: 'TR',
    region: 'Other Destinations',
    color: '#C1443C',
    tagline: 'Emerging route for trades and hospitality',
    description:
      'A newer corridor with openings in textiles, hospitality, and construction around Istanbul and Izmir.',
    whyWorkHere:
      'As one of our newer destinations, Turkey currently has less competition per opening than our established GCC routes, with employers keen to build long-term hiring relationships.',
    roleCount: 19,
    salaryRange: '\u20ba18,000–32,000/month',
    cities: ['Istanbul', 'Izmir'],
    topProfessions: ['Textiles', 'Hospitality', 'Construction'],
    visaNote:
      'Employer-sponsored work permit filed jointly by the employer and candidate through Turkish immigration.',
    applicationSteps: [
      'Resume review',
      'Employer interview',
      'Joint work permit filing',
      'Travel booking',
    ],
    faqs: [],
  },
  {
    slug: 'armenia',
    name: 'Armenia',
    isoCode: 'AM',
    region: 'Other Destinations',
    color: '#D9822B',
    tagline: 'Small but growing IT and manufacturing base',
    description:
      'A niche market centred on Yerevan, with early demand in IT support and light manufacturing roles.',
    whyWorkHere:
      'Armenia\u2019s permit process has fewer processing delays than larger markets, making it one of the fastest destinations to actually land in once an offer is confirmed.',
    roleCount: 8,
    salaryRange: '\u058f180,000–320,000/month',
    cities: ['Yerevan'],
    topProfessions: ['IT Support', 'Manufacturing', 'Hospitality'],
    visaNote:
      'Work permit sponsored by the employer, generally straightforward with fewer processing delays than larger markets.',
    applicationSteps: [
      'Resume review',
      'Employer interview',
      'Work permit filing',
      'Travel booking',
    ],
    faqs: [],
  },
  {
    slug: 'russia',
    name: 'Russia',
    isoCode: 'RU',
    region: 'Other',
    color: '#34406B',
    tagline: 'Established demand in construction and logistics',
    description:
      'Longstanding openings in construction and manufacturing support roles across several regional hubs.',
    whyWorkHere:
      'A stable, long-running corridor for construction and manufacturing trades with consistent, predictable contract terms.',
    roleCount: 14,
    salaryRange: '\u20bd65,000–110,000/month',
    cities: ['Moscow region', 'Regional hubs'],
    topProfessions: ['Construction', 'Manufacturing', 'Logistics'],
    visaNote:
      'Employer-sponsored work invitation, processed through regional migration authorities before visa issuance.',
    applicationSteps: [
      'Resume review',
      'Employer interview',
      'Work invitation and visa filing',
      'Travel booking',
    ],
    faqs: [],
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    isoCode: 'GE',
    region: 'Other Destinations',
    color: '#4C7A3E',
    tagline: 'Newest corridor, hospitality-led',
    description:
      'Our newest destination, led by hospitality demand in Tbilisi and Batumi with early construction and IT-support openings.',
    whyWorkHere:
      'Many roles qualify for a simplified short-stay process before permit conversion, making Georgia one of the fastest destinations to start working in after arrival.',
    roleCount: 11,
    salaryRange: '\u20be1,200–2,000/month',
    cities: ['Tbilisi', 'Batumi'],
    topProfessions: ['Hospitality', 'Construction', 'IT Support'],
    visaNote:
      'Employer-sponsored work permit; many roles qualify for a simplified short-stay process before permit conversion.',
    applicationSteps: [
      'Resume review',
      'Employer interview',
      'Short-stay entry, then permit conversion',
      'Travel booking',
    ],
    faqs: [],
  },
  {
    slug: 'poland',
    name: 'Poland',
    isoCode: 'PL',
    region: 'Europe',
    color: '#B83245',
    tagline: 'Fast-growing manufacturing opportunities',
    description:
      'Poland continues to hire international workers across manufacturing, warehousing, logistics, food processing, and construction sectors.',
    whyWorkHere:
      'Strong demand for workers, lower language barriers for entry-level roles, and growing employer sponsorship programs.',
    roleCount: 26,
    salaryRange: 'PLN 4,500–8,000/month',
    cities: ['Warsaw', 'Krakow', 'Wroclaw'],
    topProfessions: ['Manufacturing', 'Logistics', 'Construction'],
    visaNote: 'Employer-sponsored work permit and national work visa.',
    applicationSteps: [
      'Resume screening',
      'Employer interview',
      'Work permit processing',
      'Visa application',
    ],
    faqs: [],
  },

  {
    slug: 'romania',
    name: 'Romania',
    isoCode: 'RO',
    region: 'Europe',
    color: '#385EA8',
    tagline: 'Popular destination for skilled workers',
    description:
      'Romania has become a major destination for construction workers, welders, electricians, and factory workers.',
    whyWorkHere: 'Large number of vacancies and relatively straightforward work permit process.',
    roleCount: 24,
    salaryRange: '€700–1,500/month',
    cities: ['Bucharest', 'Cluj-Napoca'],
    topProfessions: ['Construction', 'Manufacturing', 'Hospitality'],
    visaNote: 'Employer-sponsored work authorization and residence permit.',
    applicationSteps: ['Application review', 'Interview', 'Permit filing', 'Visa issuance'],
    faqs: [],
  },

  {
    slug: 'croatia',
    name: 'Croatia',
    isoCode: 'HR',
    region: 'Europe',
    color: '#A83B32',
    tagline: 'Growing hospitality market',
    description:
      'Hotels, restaurants, and construction companies continue to recruit international workers.',
    whyWorkHere: 'Seasonal and permanent opportunities with increasing international hiring.',
    roleCount: 15,
    salaryRange: '€900–1,800/month',
    cities: ['Zagreb', 'Split'],
    topProfessions: ['Hospitality', 'Construction'],
    visaNote: 'Employer-sponsored work and residence permit.',
    applicationSteps: [
      'Resume review',
      'Employer interview',
      'Permit submission',
      'Travel preparation',
    ],
    faqs: [],
  },

  {
    slug: 'serbia',
    name: 'Serbia',
    isoCode: 'RS',
    region: 'Europe',
    color: '#3655A3',
    tagline: 'Expanding industrial recruitment',
    description: 'Industrial plants and logistics projects are increasing international hiring.',
    whyWorkHere: 'Growing manufacturing sector with international employer demand.',
    roleCount: 12,
    salaryRange: '€700–1,400/month',
    cities: ['Belgrade', 'Novi Sad'],
    topProfessions: ['Manufacturing', 'Logistics'],
    visaNote: 'Employer-sponsored temporary residence and work permit.',
    applicationSteps: ['Application review', 'Interview', 'Permit process', 'Travel'],
    faqs: [],
  },

  {
    slug: 'malta',
    name: 'Malta',
    isoCode: 'MT',
    region: 'Europe',
    color: '#C49C3A',
    tagline: 'Hospitality and service sector demand',
    description: 'Hotels, restaurants and service businesses regularly hire overseas workers.',
    whyWorkHere: 'English-speaking environment and EU-standard employment protections.',
    roleCount: 10,
    salaryRange: '€1,000–2,000/month',
    cities: ['Valletta', 'Sliema'],
    topProfessions: ['Hospitality', 'Customer Service'],
    visaNote: 'Single Permit sponsored by employer.',
    applicationSteps: ['Interview', 'Offer letter', 'Permit application', 'Travel'],
    faqs: [],
  },

  {
    slug: 'malaysia',
    name: 'Malaysia',
    isoCode: 'MY',
    region: 'Asia',
    color: '#267A58',
    tagline: 'Consistent manufacturing hiring',
    description:
      'Factories, logistics operators, and service industries regularly recruit foreign workers.',
    whyWorkHere: 'Good living standards and large international workforce.',
    roleCount: 22,
    salaryRange: 'MYR 1,800–4,000/month',
    cities: ['Kuala Lumpur', 'Johor Bahru'],
    topProfessions: ['Manufacturing', 'Logistics', 'Hospitality'],
    visaNote: 'Employer-sponsored employment pass or work permit.',
    applicationSteps: ['Screening', 'Interview', 'Permit filing', 'Departure'],
    faqs: [],
  },

  {
    slug: 'singapore',
    name: 'Singapore',
    isoCode: 'SG',
    region: 'Asia',
    color: '#D93E3E',
    tagline: 'Premium destination for skilled workers',
    description:
      'High-demand destination for technical, logistics, marine, and hospitality professionals.',
    whyWorkHere: 'Excellent salaries and world-class working environment.',
    roleCount: 18,
    salaryRange: 'SGD 1,800–4,500/month',
    cities: ['Singapore'],
    topProfessions: ['Technical Trades', 'Marine', 'Hospitality'],
    visaNote: 'Work Permit, S Pass, or Employment Pass depending on role.',
    applicationSteps: ['Interview', 'Offer', 'Work pass application', 'Travel'],
    faqs: [],
  },

  {
    slug: 'japan',
    name: 'Japan',
    isoCode: 'JP',
    region: 'Asia',
    color: '#BC3131',
    tagline: 'Technical trainee and skilled worker opportunities',
    description: 'Growing demand under Japan’s Specified Skilled Worker programs.',
    whyWorkHere: 'Long-term growth opportunities and strong worker protections.',
    roleCount: 16,
    salaryRange: '¥180,000–350,000/month',
    cities: ['Tokyo', 'Osaka'],
    topProfessions: ['Manufacturing', 'Caregiving', 'Construction'],
    visaNote: 'Specified Skilled Worker (SSW) or Technical Intern visa.',
    applicationSteps: ['Skill assessment', 'Interview', 'Visa processing', 'Relocation'],
    faqs: [],
  },

  {
    slug: 'south-korea',
    name: 'South Korea',
    isoCode: 'KR',
    region: 'Asia',
    color: '#4361C9',
    tagline: 'High-demand manufacturing sector',
    description:
      'South Korean employers regularly hire workers for factories and industrial roles.',
    whyWorkHere: 'Competitive salaries and stable employment contracts.',
    roleCount: 14,
    salaryRange: '₩2,000,000–3,500,000/month',
    cities: ['Seoul', 'Busan'],
    topProfessions: ['Manufacturing', 'Industrial'],
    visaNote: 'EPS employment permit program.',
    applicationSteps: ['Language test', 'Employer matching', 'Visa processing', 'Travel'],
    faqs: [],
  },
];

export function getCountryBySlug(slug) {
  return countries.find((c) => c.slug === slug);
}

export const featuredDrives = [
  {
    id: 1,
    title: 'Emaar Dubai Mega Recruitment Drive',
    country: 'United Arab Emirates',
    type: 'Recruitment Drive',
    vacancies: 275,
    image: 'https://picsum.photos/800/500?random=1',
    slug: '/recruitment-drives/emaar-dubai-mega-hiring',
  },
  {
    id: 2,
    title: 'NEOM Project Mega Hiring',
    country: 'Saudi Arabia',
    type: 'Recruitment Drive',
    vacancies: 450,
    image: 'https://picsum.photos/800/500?random=2',
    slug: '/recruitment-drive/neom-project-hiring-saudi',
  },
  {
    id: 3,
    title: 'Qatar Hospitality Recruitment Campaign',
    country: 'Qatar',
    type: 'Recruitment Drive',
    vacancies: 120,
    image: 'https://picsum.photos/800/500?random=3',
    slug: '/recruitment-drive/qatar-hospitality-hiring',
  },
];

export const featuredJobs = [
  {
    id: 1,
    title: 'AC Technician',
    country: 'United Arab Emirates',
    type: 'Job',
    vacancies: 35,
    image: 'https://picsum.photos/800/500?random=11',
    slug: '/jobs/ac-technician-uae',
  },
  {
    id: 2,
    title: 'Electrician',
    country: 'United Arab Emirates',
    type: 'Job',
    vacancies: 50,
    image: 'https://picsum.photos/800/500?random=12',
    slug: '/jobs/electrician-uae',
  },
  {
    id: 3,
    title: 'HVAC Technician',
    country: 'Saudi Arabia',
    type: 'Job',
    vacancies: 20,
    image: 'https://picsum.photos/800/500?random=13',
    slug: '/jobs/hvac-technician-saudi',
  },
  {
    id: 4,
    title: 'Pipe Fitter',
    country: 'Qatar',
    type: 'Job',
    vacancies: 25,
    image: 'https://picsum.photos/800/500?random=14',
    slug: '/jobs/pipe-fitter-qatar',
  },
  {
    id: 5,
    title: 'Welder',
    country: 'Kuwait',
    type: 'Job',
    vacancies: 40,
    image: 'https://picsum.photos/800/500?random=15',
    slug: '/jobs/welder-kuwait',
  },
  {
    id: 6,
    title: 'Forklift Operator',
    country: 'Germany',
    type: 'Job',
    vacancies: 18,
    image: 'https://picsum.photos/800/500?random=16',
    slug: '/jobs/forklift-operator-germany',
  },
];
